local lua_abbrevs = {
    def = "defines",
    func = "function",
    g = "global",
    l = "local",
    neq = "name =",
    teq = "type =",
}

local text_abbrevs = {
    acessed = "accessed",
    america = "America",
    api = "API",
    appriciated = "appreciated",
    bernoulli = "Bernoulli",
    canada = "Canada",
    cant = "can't",
    carreer = "career",
    celcius = "Celsius",
    centripedal = "centripetal",
    consistant = "consistent",
    continous = "continuous",
    darwin = "Darwin",
    dependant = "dependent",
    didnt = "didn't",
    disterbance = "disturbance",
    disterbence = "disturbance",
    dont = "don't",
    eachother = "each other",
    english = "English",
    friday = "Friday",
    german = "German",
    goverment = "government",
    grey = "gray",
    greyscale = "grayscale",
    gurantee = "guarantee",
    gurantees = "guarantees",
    havent = "haven't",
    hes = "he's",
    i = "I",
    idk = "I don't know",
    im = "I'm",
    independant = "independent",
    isnt = "isn't",
    isostacy = "isostasy",
    ive = "I've",
    iwth = "with",
    judgement = "judgment",
    jurassic = "Jurassic",
    licence = "license",
    maintenence = "maintenance",
    maximising = "maximizing",
    monday = "Monday",
    neccesary = "necessary",
    neccessary = "necessary",
    noah = "Noah",
    noticeible = "noticeable",
    occor = "occur",
    occored = "occurred",
    occorring = "occurring",
    occured = "occurred",
    occurence = "occurrence",
    occuring = "occurring",
    oppertunities = "opportunities",
    oppertunity = "opportunity",
    optimise = "optimize",
    paralell = "parallel",
    percieve = "perceive",
    personell = "personnel",
    probablity = "probability",
    protien = "protein",
    protiens = "proteins",
    reccomended = "recommended",
    recieve = "receive",
    recieved = "received",
    recieving = "receiving",
    rememver = "remember",
    sattelite = "satellite",
    sattellite = "satellite",
    saturday = "Saturday",
    seperate = "separate",
    seperated = "separated",
    seperating = "separating",
    seperation = "separation",
    sofware = "software",
    sophmore = "sophomore",
    sunday = "Sunday",
    suprised = "surprised",
    suprized = "surprised",
    teh = "the",
    tf2 = "Team Fortress 2",
    tge = "the",
    thats = "that's",
    theyd = "they'd",
    theyre = "they're",
    thier = "their",
    thursday = "Thursday",
    troph = "trough",
    tset = "test",
    tuesday = "Tuesday",
    unlicence = "unlicense",
    varience = "variance",
    wasnt = "wasn't",
    wednesday = "Wednesday",
    weve = "we've",
    wiki = "Wiki",
    wont = "won't",
    wouldve = "would've",
    youre = "you're",
}

local function add_abbrevs(tbl)
    for lhs, rhs in pairs(tbl) do
        vim.cmd(("iabbrev <buffer> %s %s"):format(lhs, rhs))
    end
end

vim.api.nvim_create_augroup("abbrevs", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
    group = "abbrevs",
    pattern = "lua",
    callback = function()
        add_abbrevs(lua_abbrevs)
    end,
})

vim.api.nvim_create_autocmd("FileType", {
    group = "abbrevs",
    pattern = { "text", "mediawiki", "markdown" },
    callback = function()
        add_abbrevs(text_abbrevs)
    end,
})